const topic=(name,description)=>({name,description});
const phase=(title,description,topics)=>({title,description,topics});

const builtInRoadmaps={
  ai:{name:'AI Engineering',label:'AI ENGINEERING ROADMAP',description:'Build reliable products with foundation models, retrieval, tools and multimodal systems.',phases:[
    phase('Minimum prerequisites','The small conceptual foundation the course assumes—without repeating its lessons.',[
      topic('AI and ML vocabulary','AI, ML, deep learning, generative AI, training and inference'),topic('ML problem types','Classification, regression, clustering, ranking and generation'),topic('Dataset fundamentals','Samples, features, labels, dataset quality and leakage'),topic('Model-quality fundamentals','Baselines, accuracy, precision, recall, F1 and generalization'),topic('Neural-network vocabulary','Layers, weights, activation, loss and backpropagation intuition'),topic('Mathematical readiness','Algebra, basic probability, averages and numerical dimensions'),topic('Experimental thinking','Hypotheses, controlled comparisons and reproducible evidence')]),
    phase('LLM application engineering','Course Week 1 · Understand model behaviour and build a measurable model gateway.',[
      topic('Transformer architecture','Tokenization, attention, context windows and generation'),topic('LLM lifecycle','Pretraining, alignment, deployment, inference and monitoring'),topic('Generation behaviour','Temperature, top-p, stop conditions and hallucinations'),topic('Prompt and context design','System instructions, few-shot examples and context control'),topic('Structured output','Schemas, validation and recovery from malformed output'),topic('Streaming responses','Token streaming, cancellation and time to first token'),topic('Model selection and tiering','Quality, latency, cost, privacy and capability trade-offs'),topic('Build: The AI Gateway','Streaming chat backend with model routing and cost tracking')]),
    phase('RAG foundations','Course Week 2 · Ground model responses in controlled enterprise knowledge.',[
      topic('Embedding fundamentals','Text vectors, dimensions and representation quality'),topic('Vector similarity','Cosine similarity, dot product and distance intuition'),topic('Document processing','Parsing, cleaning and metadata preservation'),topic('Chunking strategies','Fixed, recursive, semantic and parent-child chunks'),topic('Vector indexing','Exact and approximate search, top-k and thresholds'),topic('Multi-tenant retrieval','Metadata filtering, authorization and tenant isolation'),topic('Grounded generation','Context assembly, citations and no-answer behaviour'),topic('Build: The Knowledge Engine','Context-aware RAG over complex documents')]),
    phase('Enterprise-grade RAG','Course Week 3 · Go beyond naive vector search with measurable retrieval engineering.',[
      topic('BM25 keyword retrieval','Inverted indexes, lexical relevance and keyword search'),topic('Hybrid search','Combining semantic and keyword candidates'),topic('Reciprocal Rank Fusion','Merging ranked lists without incompatible raw scores'),topic('Cross-encoder reranking','Rerank candidates for relevance with latency awareness'),topic('Query transformation','Rewriting, expansion, decomposition and multi-query retrieval'),topic('Dynamic query routing','Select retrieval paths based on intent'),topic('Graph RAG basics','Entities, relationships and when graph retrieval is justified'),topic('Retrieval evaluation','Precision@k, recall@k, MRR and context relevance'),topic('Build: Enterprise Search Engine','Multi-tenant hybrid search with reranking')]),
    phase('Agents and state machines','Course Week 4 · Create controlled tool-using workflows with durable state.',[
      topic('LLM vs workflow vs agent','Choose deterministic orchestration whenever the path is known'),topic('ReAct loop','Reason, act, observe and repeat within bounded limits'),topic('Reliable tool calling','Tool selection, schemas, validation and error recovery'),topic('State-machine orchestration','Explicit states, transitions, checkpoints and routing'),topic('Persistent memory','Working state, conversation memory and semantic memory'),topic('Human-in-the-loop','Pause, approve, resume and audit consequential actions'),topic('Multi-agent patterns','Supervisor-worker, planner-executor and maker-checker'),topic('Build: Persistent Operator','Tool-calling agent with Redis-backed durable context')]),
    phase('Evals and observability','Course Week 5 · Replace subjective demos with measurable quality gates.',[
      topic('Golden datasets','Versioned, representative evaluation examples'),topic('LLM evaluation','Correctness, relevance, completeness and instruction following'),topic('RAG evaluation','Retrieval quality, faithfulness and citation correctness'),topic('Agent evaluation','Tool selection, arguments, trajectories and completion rate'),topic('LLM-as-a-judge','Rubrics, pairwise scoring, bias and limitations'),topic('End-to-end tracing','Capture model, retrieval and tool execution steps'),topic('Unit economics','Latency, tokens and cost per successful task'),topic('CI/CD quality gates','Block deployments on meaningful regressions'),topic('Build: Regression & Telemetry Gate','Automated evaluation and tracing harness')]),
    phase('MCP, context and memory','Course Week 6 · Standardize safe access to enterprise capabilities.',[
      topic('Context engineering','Select, order, compress and budget model context'),topic('MCP architecture','Hosts, clients, servers and capability discovery'),topic('MCP primitives','Tools, resources and prompts'),topic('Custom MCP servers','Expose bounded enterprise operations safely'),topic('MCP clients','Discover capabilities and manage tool execution'),topic('Security boundaries','Authentication, authorization, secrets and auditing'),topic('Memory systems','Working, semantic, episodic and long-term memory'),topic('Multi-agent orchestration','Specialization, delegation and state synchronization'),topic('Build: Audited Tool Bridge','Secure standardized bridge to legacy APIs')]),
    phase('Fine-tuning and optimization','Course Week 7 · Customize and optimize models only when the evidence justifies it.',[
      topic('Fine-tuning decision framework','Choose among prompting, RAG, tools and tuning'),topic('Dataset engineering','Clean, balanced, representative input-output examples'),topic('Supervised fine-tuning','Behaviour customization and task adaptation'),topic('LoRA and QLoRA','Parameter-efficient adaptation of open-weight models'),topic('Quantization','FP16, BF16, INT8 and INT4 trade-offs'),topic('Local model serving','Memory, throughput, concurrency and cold starts'),topic('Model benchmarking','Quality, latency, cost and operational complexity'),topic('Build: Specialist Model','Fine-tune and benchmark against frontier APIs')]),
    phase('Reliability, security and system design','Course Week 8 · Design systems that remain safe and useful during failure.',[
      topic('Agentic systems at scale','Boundaries, state ownership and orchestration trade-offs'),topic('Provider resilience','Fallbacks, timeout budgets and graceful degradation'),topic('Semantic caching','Reuse safe outputs while respecting freshness'),topic('Rate and cost controls','Quotas, budgets and overload protection'),topic('Prompt injection defense','Direct and indirect attacks through user and retrieved content'),topic('PII protection','Detection, redaction, retention and tenant isolation'),topic('Maker-checker topology','Independent verification without false confidence'),topic('Build: Dual-Agent Supervisor','Secure system with provider-outage recovery')]),
    phase('Multimodal AI','Course Week 9 · Build grounded systems across text, images and voice.',[
      topic('Multimodal architecture','Modality encoders, shared spaces and cross-attention'),topic('Vision-language models','Image understanding and visual question answering'),topic('Voice AI','Streaming speech-to-text, TTS and voice activity detection'),topic('Low-latency interaction','Streaming pipelines and interruption handling'),topic('Multimodal embeddings','Cross-modal representation and retrieval'),topic('Multimodal RAG','OCR, image retrieval and timestamped citations'),topic('Multimodal evaluation','Quality, grounding and modality-specific metrics'),topic('Build: Multimodal RAG Engine','Text, image and voice knowledge system')]),
    phase('Production capstone','Course Week 10 · Combine the complete lifecycle into one defensible product.',[
      topic('Scope one coherent product','Select a real user, workflow and measurable outcome'),topic('Design the system architecture','Models, retrieval, tools, state and trust boundaries'),topic('Implement evaluation first','Golden set, quality thresholds and failure cases'),topic('Add production observability','Traces, latency, tokens, costs and error categories'),topic('Run security tests','Injection, PII, tenant isolation and tool authorization'),topic('Exercise failure recovery','Provider outage, tool errors and stale retrieval'),topic('Deploy and monitor','Release strategy, dashboards and rollback'),topic('Prepare architecture defense','Explain every quality, cost and reliability trade-off')])
  ]},
  dl:{name:'Applied Deep Learning',label:'APPLIED DEEP LEARNING ROADMAP',description:'Train, adapt, optimize and operate modern neural models without a mathematics-heavy detour.',phases:[
    phase('Minimum foundations','Learn only the concepts required to train and evaluate neural models.',[
      topic('Tensor shapes and dimensions','Scalars, vectors, matrices and tensor operations'),topic('Gradient intuition','Direction of improvement, loss and learning rate'),topic('Training and inference','Parameters, hyperparameters, batches and epochs'),topic('Dataset splits','Training, validation, test data and leakage prevention'),topic('Core metrics','Accuracy, precision, recall, F1, MAE and MSE'),topic('Generalization','Underfitting, overfitting and baselines')]),
    phase('Neural-network foundations','Understand the complete learning loop and its essential components.',[
      topic('Layers, weights and biases','How neural networks represent learnable transformations'),topic('Activation functions','ReLU, sigmoid, tanh and softmax'),topic('Forward propagation','Move inputs through layers to predictions'),topic('Loss functions','MSE, binary and categorical cross-entropy'),topic('Backpropagation','Automatic differentiation and gradient flow'),topic('Optimizers','SGD, momentum and Adam'),topic('Build: Basic neural network','Train a small classifier end to end')]),
    phase('Deep-learning training','Make training reproducible, stable and measurable.',[
      topic('Data pipelines','Loading, batching, shuffling and preprocessing'),topic('Training and validation loops','Modes, loss, gradients and optimizer steps'),topic('Learning curves','Diagnose model behaviour from train and validation history'),topic('Regularization','Dropout, weight decay and early stopping'),topic('Normalization','Input normalization and batch normalization'),topic('Training stability','Gradient clipping, initialization and unstable loss'),topic('Checkpointing','Save, resume and compare experiments'),topic('Experiment tracking','Record datasets, configurations, metrics and artefacts')]),
    phase('Computer vision and CNNs','Learn spatial representation, transfer learning and modern vision models.',[
      topic('Image tensors','Pixels, channels, resizing and normalization'),topic('Convolutions','Kernels, feature maps, stride and padding'),topic('Pooling and receptive fields','Spatial reduction and learned context'),topic('CNN architecture patterns','From classic convolutional stacks to residual networks'),topic('Data augmentation','Improve generalization through valid transformations'),topic('Transfer learning','Freeze, replace heads and fine-tune pretrained models'),topic('Vision transformers','Patch embeddings and transformer-based vision'),topic('Build: Image classifier','Compare scratch training with transfer learning')]),
    phase('Sequence models','Understand the progression from recurrent networks to attention.',[
      topic('Sequence representation','Ordered inputs, variable lengths and hidden state'),topic('Recurrent neural networks','Sequential processing and temporal dependencies'),topic('LSTM and GRU','Gating mechanisms for longer dependencies'),topic('Bidirectional models','Use past and future context when the task allows'),topic('Sequence applications','Classification, labelling, speech and forecasting'),topic('Limits of recurrence','Vanishing gradients, serial computation and long context')]),
    phase('Attention and transformers','Understand how modern sequence models are trained and adapted.',[
      topic('Query, key and value','The representation behind attention decisions'),topic('Scaled dot-product attention','Scores, scaling, masks and weighted values'),topic('Multi-head attention','Learn multiple relationship patterns in parallel'),topic('Transformer blocks','Attention, feed-forward layers, residuals and normalization'),topic('Encoder and decoder models','Representation, generation and sequence-to-sequence tasks'),topic('Training objectives','Masked tokens, next-token prediction and contrastive learning'),topic('Build: Transformer fine-tuning','Adapt a pretrained model for classification or extraction')]),
    phase('Transfer learning and fine-tuning','Adapt pretrained models efficiently with high-quality datasets.',[
      topic('Feature extraction','Use pretrained representations without full retraining'),topic('Partial and full fine-tuning','Choose which layers to update'),topic('Dataset engineering','Collection, cleaning, deduplication and label quality'),topic('Learning-rate strategy','Protect pretrained knowledge while adapting'),topic('Parameter-efficient tuning','Adapters, LoRA, QLoRA and prompt tuning'),topic('Fine-tuning evaluation','Compare base, prompted and tuned behaviours'),topic('Avoid catastrophic forgetting','Preserve general capabilities during adaptation')]),
    phase('Choose a specialization','Go deep in one applied domain before expanding sideways.',[
      topic('NLP and language models','Classification, entities, similarity and information extraction'),topic('Computer vision','Classification, detection, segmentation and document intelligence'),topic('Time-series deep learning','Temporal splits, forecasting and leakage prevention'),topic('Recommendation systems','Embeddings, two-tower retrieval and neural ranking'),topic('Reinforcement learning — optional','States, actions, rewards, policies and sequential decisions'),topic('Build: Specialization project','Deliver one measurable domain-specific model')]),
    phase('Generative deep learning','Explore the principal families behind modern generative media.',[
      topic('Autoencoders','Latent representation and reconstruction'),topic('Variational autoencoders','Probabilistic latent spaces and generation'),topic('Generative adversarial networks','Generator-discriminator training and instability'),topic('Diffusion models','Forward noise, reverse denoising and conditioning'),topic('Contrastive learning','Align representations across examples and modalities'),topic('Multimodal learning','Shared text-image-audio representation spaces')]),
    phase('Model optimization','Reduce resource requirements while preserving useful quality.',[
      topic('Mixed-precision training','FP16 and BF16 training trade-offs'),topic('Gradient accumulation','Simulate larger batches under memory constraints'),topic('Quantization','INT8 and INT4 inference with quality measurement'),topic('Pruning','Remove low-value parameters or structures'),topic('Knowledge distillation','Transfer behaviour into smaller models'),topic('Inference batching','Balance throughput and latency'),topic('Model benchmarking','Quality, size, memory, latency, throughput and cost'),topic('Build: Optimized model','Compare original and optimized versions')]),
    phase('Deployment and MLOps','Package, release and operate models as reliable software systems.',[
      topic('Model packaging','Weights, preprocessing, signatures and dependencies'),topic('Inference patterns','Batch, online, streaming and asynchronous serving'),topic('Serving performance','Warm-up, batching, concurrency and autoscaling'),topic('Release strategies','Shadow, canary, A/B and rollback'),topic('Experiment and model registry','Reproducibility, lineage and promotion'),topic('Training pipelines','Validate, train, evaluate, register and deploy'),topic('Model monitoring','Latency, data drift, output drift and performance decay'),topic('Retraining strategy','Scheduled, drift-triggered and performance-triggered updates')]),
    phase('Responsible DL and capstone','Ship a model with evidence, controls and a complete operational story.',[
      topic('Dataset provenance and bias','Know where data came from and whom it represents'),topic('Segment-level evaluation','Find quality gaps hidden by aggregate scores'),topic('Privacy and security','Sensitive data, adversarial input and supply-chain risk'),topic('Explainability','Local and global explanations appropriate to the model'),topic('Build an end-to-end model','Data, training, registry, deployment and monitoring'),topic('Load and failure testing','Validate performance and recovery under pressure'),topic('Document model limitations','Make intended use and known failure modes explicit'),topic('Prepare technical defense','Explain quality, latency, cost and ethical trade-offs')])
  ]}
};

let roadmaps={...builtInRoadmaps};
const STORAGE_KEY='neuralpath-state-v1';
const defaultState={completed:{},subCompleted:{},notes:{},timelines:{},activity:[],focusMinutes:0,theme:'dark',profileName:'',profileDesignation:'',profileConfigured:false,activeView:'overview',filters:{ai:'all',dl:'all'},openPhases:{},openTopics:{},customRoadmaps:{},roadmapOrder:['ai','dl'],deletedRoadmaps:[]};
let state=loadState();
refreshRoadmapRegistry();
let focusDuration=25*60,focusSeconds=focusDuration,focusTimer=null,focusTopicId='';

function loadState(){try{const parsed=JSON.parse(localStorage.getItem(STORAGE_KEY)||'{}');return {...defaultState,...parsed,completed:{...(parsed.completed||{})},subCompleted:{...(parsed.subCompleted||{})},notes:{...(parsed.notes||{})},timelines:{...(parsed.timelines||{})},filters:{...defaultState.filters,...(parsed.filters||{})},openPhases:{...(parsed.openPhases||{})},openTopics:{...(parsed.openTopics||{})},customRoadmaps:{...(parsed.customRoadmaps||{})},roadmapOrder:[...(parsed.roadmapOrder||defaultState.roadmapOrder)],deletedRoadmaps:[...(parsed.deletedRoadmaps||[])]};}catch{return {...defaultState,customRoadmaps:{},roadmapOrder:[...defaultState.roadmapOrder],deletedRoadmaps:[]};}}
function saveState(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state));}
function activeRoadmaps(){return roadmaps;}
function roadmapKeys(){const active=Object.keys(roadmaps),ordered=(state.roadmapOrder||[]).filter((id,index,list)=>active.includes(id)&&list.indexOf(id)===index);active.forEach(id=>{if(!ordered.includes(id))ordered.push(id);});state.roadmapOrder=ordered;return [...ordered];}
function refreshRoadmapRegistry(){const deleted=new Set(state.deletedRoadmaps||[]);roadmaps={};Object.entries(builtInRoadmaps).forEach(([id,map])=>{if(!deleted.has(id))roadmaps[id]=map;});Object.entries(state.customRoadmaps||{}).forEach(([id,map])=>{if(!deleted.has(id))roadmaps[id]=map;});roadmapKeys();}
function requiredText(value,path){if(typeof value!=='string'||!value.trim())throw new Error(`${path} must be a non-empty string.`);return value.trim();}
function requiredId(value,path){const id=requiredText(value,path);if(!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(id))throw new Error(`${path} must use lowercase kebab-case.`);return id;}
function uniqueIds(items,path){const ids=new Set();items.forEach(item=>{if(ids.has(item.id))throw new Error(`${path} contains duplicate id "${item.id}".`);ids.add(item.id);});}
function validateRoadmapImport(payload){if(!payload||payload.schemaVersion!==1)throw new Error('schemaVersion must be 1.');if(!Array.isArray(payload.roadmaps)||!payload.roadmaps.length)throw new Error('roadmaps must contain at least one roadmap.');const normalized=payload.roadmaps.map((map,mi)=>{const id=requiredId(map.id,`roadmaps[${mi}].id`),name=requiredText(map.title||map.name,`roadmaps[${mi}].title`),description=requiredText(map.description,`roadmaps[${mi}].description`);if(!Array.isArray(map.phases)||!map.phases.length)throw new Error(`${name} must contain at least one phase.`);const phases=map.phases.map((p,pi)=>{const phaseId=requiredId(p.id,`${name}.phases[${pi}].id`),title=requiredText(p.title,`${name}.phases[${pi}].title`),phaseDescription=requiredText(p.description,`${name}.phases[${pi}].description`);if(!Array.isArray(p.topics)||!p.topics.length)throw new Error(`${title} must contain at least one topic.`);const topics=p.topics.map((t,ti)=>{const topicId=requiredId(t.id,`${title}.topics[${ti}].id`),topicName=requiredText(t.title||t.name,`${title}.topics[${ti}].title`),topicDescription=requiredText(t.description,`${title}.topics[${ti}].description`);if(!Array.isArray(t.subtopics)||!t.subtopics.length)throw new Error(`${topicName} must contain at least one subtopic.`);const subtopics=t.subtopics.map((s,si)=>({id:requiredId(s.id,`${topicName}.subtopics[${si}].id`),name:requiredText(s.title||s.name,`${topicName}.subtopics[${si}].title`)}));uniqueIds(subtopics,`${topicName}.subtopics`);return {id:topicId,name:topicName,description:topicDescription,subtopics};});uniqueIds(topics,`${title}.topics`);return {id:phaseId,title,description:phaseDescription,topics};});uniqueIds(phases,`${name}.phases`);return {id,name,label:typeof map.label==='string'&&map.label.trim()?map.label.trim():`${name.toUpperCase()} ROADMAP`,description,phases,source:'custom'};});uniqueIds(normalized,'roadmaps');return normalized;}
function applyRoadmapImport(payload,{allowUpdate=false}={}){const incoming=validateRoadmapImport(payload),added=[],updated=[];incoming.forEach(map=>{if(Object.prototype.hasOwnProperty.call(builtInRoadmaps,map.id))throw new Error(`"${map.id}" is a built-in roadmap and cannot be overwritten.`);if(state.customRoadmaps[map.id]&&!allowUpdate)throw new Error(`Roadmap "${map.id}" already exists.`);});incoming.forEach(map=>{if(state.customRoadmaps[map.id])updated.push(map.id);else added.push(map.id);state.customRoadmaps[map.id]=map;if(!state.roadmapOrder.includes(map.id))state.roadmapOrder.push(map.id);state.deletedRoadmaps=state.deletedRoadmaps.filter(id=>id!==map.id);state.filters[map.id]=state.filters[map.id]||'all';});refreshRoadmapRegistry();saveState();return {added,updated};}
function moveRoadmap(id,direction){const order=roadmapKeys(),from=order.indexOf(id),to=Math.max(0,Math.min(order.length-1,from+Math.sign(direction)));if(from<0||from===to)return false;[order[from],order[to]]=[order[to],order[from]];state.roadmapOrder=order;saveState();return true;}
function deleteRoadmap(id){if(!roadmaps[id]||roadmapKeys().length<=1)return false;if(Object.prototype.hasOwnProperty.call(state.customRoadmaps,id))delete state.customRoadmaps[id];else if(!state.deletedRoadmaps.includes(id))state.deletedRoadmaps.push(id);state.roadmapOrder=state.roadmapOrder.filter(key=>key!==id);if(state.activeView===id)state.activeView='overview';refreshRoadmapRegistry();saveState();return true;}
function allTopics(trackKey){const map=roadmaps[trackKey];if(!map)return [];return map.phases.flatMap((p,pi)=>p.topics.map((t,ti)=>({...t,id:t.id?`${trackKey}-${t.id}`:`${trackKey}-${pi}-${ti}`,trackKey,phaseIndex:pi,topicIndex:ti,phaseTitle:p.title})));}
function everyTopic(){return roadmapKeys().flatMap(allTopics);}
function getTopic(id){return everyTopic().find(t=>t.id===id);}
function statsFor(trackKey){const list=allTopics(trackKey),done=list.filter(isTopicDone).length;return {total:list.length,done,pct:list.length?Math.round(done/list.length*100):0};}
function overallStats(){const list=everyTopic(),done=list.filter(isTopicDone).length;return {total:list.length,done,pct:Math.round(done/list.length*100),notes:Object.values(state.notes).filter(Boolean).length};}
function today(value=new Date()){const d=new Date(value);return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,10);}
function recordActivity(type,id){state.activity.push({date:today(),type,id,at:Date.now()});state.activity=state.activity.slice(-800);}
function streak(now=new Date()){const days=new Set(state.activity.map(a=>a.date));let n=0,d=new Date(now);d.setHours(12,0,0,0);while(days.has(today(d))){n++;d.setDate(d.getDate()-1);}return n;}
function formatStreak(days){return `${days} ${days===1?'day':'days'}`;}
function escapeHtml(value=''){return value.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function extractNoteLinks(value=''){const matches=value.match(/https?:\/\/[^\s<>"']+/gi)||[];return [...new Set(matches.map(link=>link.replace(/[),.;!?]+$/,'')).filter(Boolean))];}
function noteLinksMarkup(value=''){const links=extractNoteLinks(value);if(!links.length)return `<div class="note-links-preview empty"><span class="eyebrow">LINKS IN THIS NOTE</span><p>Paste an http:// or https:// link to open it from here.</p></div>`;return `<div class="note-links-preview"><span class="eyebrow">LINKS IN THIS NOTE</span><div class="note-link-list">${links.map((link,index)=>`<a href="${escapeHtml(link)}" target="_blank" rel="noopener noreferrer"><span>↗</span><span><strong>Open link ${index+1}</strong><small>${escapeHtml(link)}</small></span></a>`).join('')}</div></div>`;}
function highlight(value,q){if(!q)return escapeHtml(value);const safe=escapeHtml(value),needle=escapeHtml(q).replace(/[.*+?^${}()|[\]\\]/g,'\\$&');return safe.replace(new RegExp(`(${needle})`,'ig'),'<mark>$1</mark>');}
function showToast(message){const el=document.querySelector('#toast');el.textContent=message;el.classList.remove('hidden');clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>el.classList.add('hidden'),2600);}

function setHeader(eyebrow,title){document.querySelector('#pageEyebrow').textContent=eyebrow;document.querySelector('#pageTitle').textContent=title;}
function profileInitials(name){const parts=(name||'').trim().split(/\s+/).filter(Boolean);if(!parts.length)return 'VR';return `${parts[0][0]}${parts.length>1?parts[parts.length-1][0]:''}`.toUpperCase();}
function profileNeedsSetup(profileState){return profileState.profileConfigured!==true;}
function updateSidebar(){const s=overallStats(),icons=['◎','◇','◉','◆','◌','⬡'];document.querySelector('#sidebarWeek').innerHTML=`<span class="eyebrow">YOUR PROGRESS</span><strong>${s.done} of ${s.total} topics</strong><div class="mini-progress"><span style="width:${s.pct}%"></span></div><p>${s.pct?`${s.pct}% complete · keep the chain moving.`:'Your first completed topic starts the journey.'}</p>`;document.querySelector('#roadmapNav').innerHTML=roadmapKeys().map((id,index)=>`<button class="nav-item ${state.activeView===id?'active':''}" data-view="${escapeHtml(id)}"><span class="nav-icon">${icons[index%icons.length]}</span><span>${escapeHtml(roadmaps[id].name)}</span></button>`).join('');document.querySelector('#profileName').textContent=state.profileName||'Vishwa';document.querySelector('#profileDesignation').textContent=state.profileDesignation||'Learner';document.querySelector('#profileAvatar').textContent=profileInitials(state.profileName);document.querySelectorAll('.nav-item[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===state.activeView));}
function navigate(view){if(!['overview','focus',...roadmapKeys()].includes(view))view='overview';state.activeView=view;saveState();document.querySelector('#searchPanel').classList.add('hidden');document.querySelector('#globalSearch').value='';updateSidebar();if(view==='overview')renderOverview();else if(roadmaps[view])renderRoadmap(view);else renderFocus();window.scrollTo({top:0,behavior:'smooth'});}

function statCard(icon,cls,value,label){return `<article class="stat-card"><span class="stat-icon ${cls}">${icon}</span><div><strong>${value}</strong><span class="stat-label">${label}</span></div></article>`;}
function subtopicsFor(t){if(Array.isArray(t.subtopics)&&t.subtopics.length)return t.subtopics.map((s,index)=>({id:`${t.id}-sub-${s.id||index}`,name:s.name||s.title}));let parts=t.description.split(/,\s*|\s+and\s+|\s+vs\.?\s+/i).map(v=>v.trim()).filter(Boolean);if(parts.length<2)parts=[`Understand ${t.name}`,`Apply ${t.name} in a practical example`,`Review and explain ${t.name}`];else if(parts.length===2)parts.push(`Apply ${t.name} end to end`);return parts.slice(0,8).map((name,index)=>({id:`${t.id}-sub-${index}`,name:name.charAt(0).toUpperCase()+name.slice(1)}));}
function subtopicProgress(t){const subs=subtopicsFor(t),hasChildState=subs.some(s=>Object.prototype.hasOwnProperty.call(state.subCompleted,s.id));const done=state.completed[t.id]&&!hasChildState?subs.length:subs.filter(s=>state.subCompleted[s.id]).length;return {done,total:subs.length,pct:Math.round(done/subs.length*100)};}
function isTopicDone(t){const p=subtopicProgress(t);return p.done===p.total;}
function localDay(value){const d=typeof value==='string'?new Date(`${value}T00:00:00`):new Date(value);d.setHours(0,0,0,0);return d;}
function timelineStatus(timeline,now=new Date()){const start=localDay(timeline.start),deadline=localDay(timeline.deadline),current=localDay(now),day=86400000;if(current<start){const until=Math.round((start-current)/day);return {pct:0,daysLeft:Math.round((deadline-current)/day),label:`Starts in ${until} day${until===1?'':'s'}`,state:'upcoming'};}if(current>deadline){const overdue=Math.round((current-deadline)/day);return {pct:100,daysLeft:-overdue,label:`${overdue} day${overdue===1?'':'s'} overdue`,state:'overdue'};}const total=Math.max(1,Math.round((deadline-start)/day)),elapsed=Math.max(0,Math.round((current-start)/day)),daysLeft=Math.max(0,Math.round((deadline-current)/day)),pct=Math.max(0,Math.min(100,Math.round(elapsed/total*100)));return {pct,daysLeft,label:daysLeft===0?'Due today':`${daysLeft} day${daysLeft===1?'':'s'} left`,state:daysLeft===0?'due':'active'};}
function displayDate(value){return localDay(value).toLocaleDateString(undefined,{month:'short',day:'numeric'}).toUpperCase();}
function phaseTimelineMarkup(trackKey,phaseIndex,title){const id=`phase-${trackKey}-${phaseIndex}`,timeline=state.timelines[id],attrs=`data-action="phase-timeline" data-track="${trackKey}" data-phase-index="${phaseIndex}" aria-label="Set timeline for ${escapeHtml(title)}"`;if(!timeline)return `<button class="deadline-horizon phase-horizon empty" ${attrs}><span>Set a calendar timeline for this main topic</span><strong>＋ Add dates</strong></button>`;const status=timelineStatus(timeline);return `<button class="deadline-horizon phase-horizon configured ${status.state}" ${attrs}><span class="horizon-meta"><span>START · ${displayDate(timeline.start)}</span><strong>${status.label}</strong><span>DUE · ${displayDate(timeline.deadline)}</span></span><span class="horizon-track"><i class="horizon-fill" style="width:${status.pct}%"></i><span class="horizon-marker" style="left:${status.pct}%" aria-label="${status.pct}% of timeline elapsed"></span></span></button>`;}
function topicRow(t){const subs=subtopicsFor(t),sp=subtopicProgress(t),done=sp.done===sp.total,hasNote=!!state.notes[t.id],open=!!state.openTopics[t.id];return `<div class="topic-shell ${done?'completed':''} ${open?'open':''}" data-topic-id="${t.id}"><div class="topic-row"><button class="check" data-action="toggle" aria-label="${done?'Mark all subtopics incomplete':'Mark all subtopics complete'}">${done?'✓':''}</button><button class="topic-toggle" data-action="topic" aria-expanded="${open}"><span class="topic-copy"><strong>${escapeHtml(t.name)}</strong><span>${escapeHtml(t.description)}</span></span><span class="subtopic-count">${phaseCountLabel(sp.done,sp.total)}</span><span class="topic-chevron">⌄</span></button><button class="note-btn ${hasNote?'':'muted'}" data-action="note">${hasNote?'Note added':'+ Note'}</button></div><div class="topic-details"><p>${escapeHtml(t.description)}</p><div class="subtopic-list">${subs.map((s,index)=>{const checked=state.completed[t.id]&&!Object.keys(state.subCompleted).some(k=>k.startsWith(`${t.id}-sub-`))||!!state.subCompleted[s.id],childHasNote=!!state.notes[s.id];return `<div class="subtopic-row ${checked?'completed':''}"><button class="sub-check" data-action="subtoggle" data-sub-index="${index}" aria-label="${checked?'Mark subtopic incomplete':'Mark subtopic complete'}">${checked?'✓':''}</button><span>${escapeHtml(s.name)}</span><button class="sub-note-btn ${childHasNote?'has-note':''}" data-action="subnote" data-sub-index="${index}">${childHasNote?'Note added':'+ Note'}</button></div>`;}).join('')}</div><div class="topic-detail-footer"><span>${hasNote?'Learning note saved':'No parent-topic note yet'}</span><button class="text-btn" data-action="note">${hasNote?'Open parent note':'Add parent note'} →</button></div></div></div>`;}
function nextTopic(){return everyTopic().find(t=>!isTopicDone(t))||everyTopic()[0];}
function weekData(){const out=[];for(let i=6;i>=0;i--){const d=new Date();d.setDate(d.getDate()-i);const key=d.toISOString().slice(0,10);out.push({label:d.toLocaleDateString(undefined,{weekday:'narrow'}),count:state.activity.filter(a=>a.date===key).length});}return out;}
function roadmapProgressListMarkup(tracks,colors=['var(--violet)','var(--cyan)','var(--amber)','var(--rose)']){return `<div class="roadmap-progress-list">${tracks.map((track,index)=>`<div class="roadmap-progress-item" style="--roadmap-color:${colors[index%colors.length]}"><div class="roadmap-progress-head"><span><i>${String(index+1).padStart(2,'0')}</i>${escapeHtml(track.map.name)}</span><strong>${track.stats.pct}%</strong></div><div class="roadmap-progress-bar"><span style="width:${track.stats.pct}%"></span></div><small>${track.stats.done}/${track.stats.total} topics</small></div>`).join('')}</div>`;}

function renderOverview(){setHeader('LEARNING COMMAND CENTER','Build momentum, one concept at a time.');const s=overallStats(),tracks=roadmapKeys().map((id,index)=>({id,index,map:roadmaps[id],stats:statsFor(id)})),next=nextTopic(),phaseObj=roadmaps[next.trackKey].phases[next.phaseIndex],activePhaseProgress=phaseProgress(next.trackKey,next.phaseIndex);const phaseTopics=allTopics(next.trackKey).filter(t=>t.phaseIndex===next.phaseIndex).slice(0,4);const colors=['var(--violet)','var(--cyan)','var(--amber)','var(--rose)'];document.querySelector('#app').innerHTML=`
  <section class="stats-grid" aria-label="Learning statistics"><article class="stat-card accent"><span class="stat-label">Overall progress</span><div class="stat-row"><strong>${s.pct}%</strong><span class="trend">${s.done} topics mastered</span></div><div class="progress-bar"><span style="width:${s.pct}%"></span></div></article>${statCard('✓','violet',s.done,'Topics completed')}${statCard('↗','amber',formatStreak(streak()),'Current streak')}${statCard('◷','cyan',formatMinutes(state.focusMinutes),'Focused learning')}</section>
  <section class="section-heading"><div><span class="eyebrow">CONTINUE LEARNING</span><h2>Your active roadmap</h2></div><button class="text-btn" data-view="${next.trackKey}">View full roadmap →</button></section>
  <div class="overview-grid"><article class="panel continue-card"><div class="continue-head"><div class="phase-badge">${String(next.phaseIndex).padStart(2,'0')}</div><div class="continue-copy"><span class="eyebrow">${roadmaps[next.trackKey].name.toUpperCase()} · PHASE ${next.phaseIndex}</span><h3>${escapeHtml(phaseObj.title)}</h3><p>${escapeHtml(phaseObj.description)}</p></div><span class="phase-count-badge">${phaseCountLabel(activePhaseProgress.done,activePhaseProgress.total)}</span></div><div class="topic-preview">${phaseTopics.map(topicRow).join('')}</div></article>
  <aside class="panel insight-panel roadmap-progress-panel"><span class="eyebrow">ROADMAP PROGRESS</span><h3>Progress by roadmap</h3><p class="roadmap-progress-copy">Your current topic completion across every learning path.</p>${roadmapProgressListMarkup(tracks,colors)}</aside></div>`;
}

function phaseCountLabel(done,total){return `(${done}/${total})`;}
function phaseProgress(trackKey,pi){const topics=allTopics(trackKey).filter(t=>t.phaseIndex===pi),done=topics.filter(isTopicDone).length;return {total:topics.length,done,pct:Math.round(done/topics.length*100)};}
function filteredTopics(trackKey,pi,filter,q=''){return allTopics(trackKey).filter(t=>t.phaseIndex===pi).filter(t=>{if(q&&!`${t.name} ${t.description} ${t.phaseTitle}`.toLowerCase().includes(q.toLowerCase()))return false;if(filter==='done')return isTopicDone(t);if(filter==='todo')return !isTopicDone(t);if(filter==='notes')return !!state.notes[t.id]||subtopicsFor(t).some(s=>!!state.notes[s.id]);return true;});}
function renderRoadmap(trackKey,q=''){const map=roadmaps[trackKey],s=statsFor(trackKey),filter=state.filters[trackKey]||'all';setHeader(map.label,map.name);const cards=map.phases.map((p,pi)=>{const ps=phaseProgress(trackKey,pi),topics=filteredTopics(trackKey,pi,filter,q);if(!topics.length&&(q||filter!=='all'))return '';const key=`${trackKey}-${pi}`,open=state.openPhases[key]??(ps.done<ps.total&&map.phases.slice(0,pi).every((_,i)=>phaseProgress(trackKey,i).done===phaseProgress(trackKey,i).total));return `<article class="phase-card ${open?'open':''} ${ps.done===ps.total?'done':''}" data-phase="${key}"><button class="phase-toggle" data-action="phase"><span class="phase-index">${ps.done===ps.total?'✓':String(pi).padStart(2,'0')}</span><span class="phase-name"><h3>${highlight(p.title,q)}</h3><p>${highlight(p.description,q)}</p></span><span class="phase-meter"><strong>${phaseCountLabel(ps.done,ps.total)}</strong><span class="mini-progress"><span style="width:${ps.pct}%"></span></span></span><span class="chevron">⌄</span></button>${phaseTimelineMarkup(trackKey,pi,p.title)}<div class="phase-topics"><div class="phase-description">${highlight(p.description,q)}</div>${topics.map(t=>topicRow(t).replace(escapeHtml(t.name),highlight(t.name,q)).replace(escapeHtml(t.description),highlight(t.description,q))).join('')}</div></article>`;}).join('');document.querySelector('#app').innerHTML=`<div class="roadmap-toolbar"><div class="track-summary"><span class="eyebrow">${map.label}</span><h2>${escapeHtml(map.name)}</h2><p>${escapeHtml(map.description)}</p></div><div class="roadmap-total"><strong>${s.pct}%</strong><span>${s.done} of ${s.total} complete</span></div></div><div class="filter-row">${[['all','All topics'],['todo','To learn'],['done','Completed'],['notes','With notes']].map(([id,label])=>`<button class="filter-chip ${filter===id?'active':''}" data-filter="${id}" data-track="${trackKey}">${label}</button>`).join('')}</div><div class="phase-list">${cards||'<div class="panel empty-card">No topics match this filter.</div>'}</div>`;}

function formatMinutes(min){if(min<60)return `${min}m`;return `${Math.floor(min/60)}h ${min%60}m`;}
function renderFocus(){setHeader('DEEP WORK','Turn intention into focused progress.');const unfinished=everyTopic().filter(t=>!isTopicDone(t));if(!focusTopicId||!getTopic(focusTopicId)||isTopicDone(getTopic(focusTopicId)))focusTopicId=(unfinished[0]||everyTopic()[0]).id;const current=getTopic(focusTopicId);document.querySelector('#app').innerHTML=`<div class="focus-layout"><section class="panel focus-main"><span class="eyebrow">FOCUS TIMER</span><div class="focus-orb" id="focusOrb" style="--timer-progress:0deg"><div class="timer" id="timerText">${formatTimer(focusSeconds)}</div></div><div class="focus-topic"><span>${roadmaps[current.trackKey].name.toUpperCase()} · ${escapeHtml(current.phaseTitle)}</span><h2>${escapeHtml(current.name)}</h2><p>${escapeHtml(current.description)}</p></div><div class="focus-actions"><button class="primary-btn" id="timerToggle">Start session</button><button class="secondary-btn" id="timerReset">Reset</button><button class="secondary-btn" data-topic-id="${current.id}" data-action="toggle">Mark complete</button></div></section><aside class="panel focus-side"><span class="eyebrow">SESSION SETUP</span><h3>Choose your next target</h3><select class="focus-select" id="focusSelect">${unfinished.map(t=>`<option value="${t.id}" ${t.id===focusTopicId?'selected':''}>${escapeHtml(roadmaps[t.trackKey].name)} · ${escapeHtml(t.name)}</option>`).join('')}</select><span class="eyebrow">DURATION</span><div class="duration-options">${[25,45,60].map(m=>`<button class="duration ${focusDuration===m*60?'active':''}" data-minutes="${m}">${m} min</button>`).join('')}</div><div class="session-stats"><div class="session-stat"><strong>${formatMinutes(state.focusMinutes)}</strong><span>TOTAL FOCUS</span></div><div class="session-stat"><strong>${streak()}</strong><span>DAY STREAK</span></div></div></aside></div>`;wireTimer();}
function formatTimer(sec){return `${String(Math.floor(sec/60)).padStart(2,'0')}:${String(sec%60).padStart(2,'0')}`;}
function wireTimer(){document.querySelector('#timerToggle').addEventListener('click',toggleTimer);document.querySelector('#timerReset').addEventListener('click',resetTimer);document.querySelector('#focusSelect').addEventListener('change',e=>{focusTopicId=e.target.value;resetTimer();renderFocus();});document.querySelectorAll('.duration').forEach(b=>b.addEventListener('click',()=>{focusDuration=Number(b.dataset.minutes)*60;resetTimer();renderFocus();}));}
function toggleTimer(){const btn=document.querySelector('#timerToggle');if(focusTimer){clearInterval(focusTimer);focusTimer=null;btn.textContent='Resume session';return;}btn.textContent='Pause';focusTimer=setInterval(()=>{focusSeconds--;updateTimerUI();if(focusSeconds<=0){clearInterval(focusTimer);focusTimer=null;state.focusMinutes+=Math.round(focusDuration/60);recordActivity('focus',focusTopicId);focusSeconds=focusDuration;saveState();showToast('Focus session complete — excellent work.');renderFocus();}},1000);}
function updateTimerUI(){const text=document.querySelector('#timerText'),orb=document.querySelector('#focusOrb');if(text)text.textContent=formatTimer(focusSeconds);if(orb)orb.style.setProperty('--timer-progress',`${(1-focusSeconds/focusDuration)*360}deg`);}
function resetTimer(){if(focusTimer)clearInterval(focusTimer);focusTimer=null;focusSeconds=focusDuration;updateTimerUI();}

function toggleTopic(id){const t=getTopic(id),target=!isTopicDone(t);subtopicsFor(t).forEach(s=>state.subCompleted[s.id]=target);state.completed[id]=target;recordActivity(target?'complete':'reopen',id);saveState();showToast(target?'Topic and subtopics completed ✓':'Topic and subtopics reopened');rerender();}
function toggleSubtopic(id,index){const t=getTopic(id),subs=subtopicsFor(t),hasChildState=subs.some(s=>Object.prototype.hasOwnProperty.call(state.subCompleted,s.id));if(state.completed[id]&&!hasChildState)subs.forEach(s=>state.subCompleted[s.id]=true);const child=subs[index];state.subCompleted[child.id]=!state.subCompleted[child.id];const progress=subtopicProgress(t);state.completed[id]=progress.done===progress.total;recordActivity(state.subCompleted[child.id]?'sub-complete':'sub-reopen',child.id);saveState();showToast(state.subCompleted[child.id]?'Subtopic completed ✓':'Subtopic reopened');rerender();}
function openNote(id,subIndex=null){const t=getTopic(id),sub=subIndex===null?null:subtopicsFor(t)[subIndex],noteId=sub?sub.id:id,title=sub?sub.name:t.name,subtitle=sub?`${t.name} · ${t.phaseTitle}`:t.phaseTitle,existing=state.notes[noteId]||'';openModal(`<span class="eyebrow">${sub?'SUBTOPIC NOTE':'TOPIC NOTE'}</span><h2 id="modalTitle">${escapeHtml(title)}</h2><p class="modal-subtitle">${escapeHtml(subtitle)} · Notes are saved on this device.</p><textarea class="notes-area" id="noteText" placeholder="Capture an insight, question, example or useful resource…">${escapeHtml(existing)}</textarea><div id="noteLinksPreview">${noteLinksMarkup(existing)}</div><div class="modal-actions"><button class="secondary-btn" id="deleteNote">Clear</button><button class="primary-btn" id="saveNote">Save note</button></div>`);const noteText=document.querySelector('#noteText'),preview=document.querySelector('#noteLinksPreview');noteText.focus();noteText.addEventListener('input',()=>preview.innerHTML=noteLinksMarkup(noteText.value));document.querySelector('#saveNote').onclick=()=>{state.notes[noteId]=noteText.value.trim();recordActivity('note',noteId);saveState();closeModal();showToast('Note saved');rerender();};document.querySelector('#deleteNote').onclick=()=>{delete state.notes[noteId];saveState();closeModal();showToast('Note cleared');rerender();};}
function openProfileEditor(firstTime=false){openModal(`<span class="eyebrow">${firstTime?'WELCOME TO NEURALPATH':'PROFILE'}</span><h2 id="modalTitle">${firstTime?'Set up your learning profile':'Edit your profile'}</h2><p class="modal-subtitle">${firstTime?'Tell us how you would like to appear in your learning dashboard.':'Your profile is stored locally with your progress.'}</p><label class="profile-label" for="profileNameInput">Name</label><input class="profile-input" id="profileNameInput" maxlength="60" value="${escapeHtml(state.profileName||'')}" placeholder="Enter your name"><label class="profile-label profile-label-spaced" for="profileDesignationInput">Designation</label><input class="profile-input" id="profileDesignationInput" maxlength="80" value="${escapeHtml(state.profileDesignation||'')}" placeholder="Example: SDE 2, Backend Engineer"><div class="modal-actions"><button class="primary-btn" id="saveProfile">${firstTime?'Start learning':'Save profile'}</button></div>`);if(firstTime){document.querySelector('#modalBackdrop').dataset.locked='true';document.querySelector('#modalClose').classList.add('hidden');}const nameInput=document.querySelector('#profileNameInput'),designationInput=document.querySelector('#profileDesignationInput');nameInput.focus();nameInput.select();const save=()=>{const name=nameInput.value.trim(),designation=designationInput.value.trim();if(!name||!designation){showToast('Please enter both name and designation.');return;}state.profileName=name;state.profileDesignation=designation;state.profileConfigured=true;saveState();closeModal(true);updateSidebar();showToast(firstTime?'Profile ready — welcome!':'Profile updated');};document.querySelector('#saveProfile').onclick=save;[nameInput,designationInput].forEach(input=>input.addEventListener('keydown',e=>{if(e.key==='Enter')save();}));}
function openTimeline(id,title){const existing=state.timelines[id]||{},start=existing.start||today(),deadline=existing.deadline||'';openModal(`<span class="eyebrow">MAIN TOPIC TIMELINE</span><h2 id="modalTitle">${escapeHtml(title)}</h2><p class="modal-subtitle">The horizon represents calendar time elapsed. It does not change your learning-completion count.</p><div class="date-grid"><label class="profile-label">Start date<input class="profile-input" id="timelineStart" type="date" value="${start}"></label><label class="profile-label">Deadline<input class="profile-input" id="timelineDeadline" type="date" value="${deadline}"></label></div><div class="modal-actions">${existing.deadline?'<button class="secondary-btn" id="clearTimeline">Clear timeline</button>':''}<button class="primary-btn" id="saveTimeline">Save timeline</button></div>`);const startInput=document.querySelector('#timelineStart'),deadlineInput=document.querySelector('#timelineDeadline');document.querySelector('#saveTimeline').onclick=()=>{if(!startInput.value||!deadlineInput.value){showToast('Choose both a start date and deadline.');return;}if(localDay(deadlineInput.value)<localDay(startInput.value)){showToast('Deadline must be on or after the start date.');return;}state.timelines[id]={start:startInput.value,deadline:deadlineInput.value};recordActivity('timeline',id);saveState();closeModal();showToast('Timeline saved');rerender();};const clear=document.querySelector('#clearTimeline');if(clear)clear.onclick=()=>{delete state.timelines[id];saveState();closeModal();showToast('Timeline cleared');rerender();};}
function openModal(html){const backdrop=document.querySelector('#modalBackdrop');delete backdrop.dataset.locked;document.querySelector('#modalClose').classList.remove('hidden');document.querySelector('#modalContent').innerHTML=html;backdrop.classList.remove('hidden');}
function closeModal(force=false){const backdrop=document.querySelector('#modalBackdrop');if(backdrop.dataset.locked==='true'&&!force)return;backdrop.classList.add('hidden');delete backdrop.dataset.locked;document.querySelector('#modalClose').classList.remove('hidden');}
function rerender(){if(state.activeView==='overview')renderOverview();else if(state.activeView==='focus')renderFocus();else renderRoadmap(state.activeView);updateSidebar();}
function openAddRoadmapModal(){openModal(`<span class="eyebrow">EXPAND YOUR LEARNING PATH</span><h2 id="modalTitle">Add a roadmap</h2><p class="modal-subtitle">Upload a NeuralPath roadmap JSON file. New roadmap IDs are added without changing your existing roadmaps or learning data.</p><div class="roadmap-upload"><span>JSON</span><strong>Choose your roadmap file</strong><p>Schema version 1 · one or multiple roadmaps</p><button class="primary-btn" id="chooseRoadmapFile">Select JSON file</button></div><div class="import-hint"><strong>Required hierarchy</strong><code>roadmaps → phases → topics → subtopics</code></div>`);document.querySelector('#chooseRoadmapFile').onclick=()=>document.querySelector('#roadmapInput').click();}
function openRoadmapManager(){const keys=roadmapKeys();openModal(`<span class="eyebrow">CUSTOM SETTINGS</span><h2 id="modalTitle">Manage roadmaps</h2><p class="modal-subtitle">Priority controls the order in the sidebar and dashboard. Removing a roadmap preserves its notes, progress and deadlines.</p><div class="roadmap-manager">${keys.map((id,index)=>`<div class="roadmap-manage-row"><span class="priority-number">${index+1}</span><span class="roadmap-manage-copy"><strong>${escapeHtml(roadmaps[id].name)}</strong><small>${Object.prototype.hasOwnProperty.call(builtInRoadmaps,id)?'BUILT-IN':'IMPORTED'} · ${allTopics(id).length} topics</small></span><span class="priority-actions"><button class="manager-icon" data-action="roadmap-up" data-roadmap-id="${escapeHtml(id)}" ${index===0?'disabled':''} aria-label="Increase priority">↑</button><button class="manager-icon" data-action="roadmap-down" data-roadmap-id="${escapeHtml(id)}" ${index===keys.length-1?'disabled':''} aria-label="Decrease priority">↓</button><button class="manager-icon remove" data-action="roadmap-delete" data-roadmap-id="${escapeHtml(id)}" ${keys.length===1?'disabled':''} aria-label="Delete roadmap">×</button></span></div>`).join('')}</div><div class="modal-actions"><button class="secondary-btn" id="managerAddRoadmap">＋ Add roadmap</button></div>`);document.querySelector('#managerAddRoadmap').onclick=openAddRoadmapModal;}
function importRoadmapFile(file){const reader=new FileReader();reader.onload=()=>{try{const payload=JSON.parse(reader.result),incoming=validateRoadmapImport(payload),existing=incoming.filter(map=>state.customRoadmaps[map.id]);incoming.forEach(map=>{if(Object.prototype.hasOwnProperty.call(builtInRoadmaps,map.id))throw new Error(`"${map.id}" is a built-in roadmap and cannot be overwritten.`);});const allowUpdate=!existing.length||confirm(`${existing.length} roadmap${existing.length===1?'':'s'} already exist. Update ${existing.map(map=>map.name).join(', ')}?`);if(!allowUpdate)return;const result=applyRoadmapImport(payload,{allowUpdate:true}),target=result.added[0]||result.updated[0];closeModal();updateSidebar();showToast(`${result.added.length} added · ${result.updated.length} updated`);if(target)navigate(target);}catch(error){showToast(error instanceof SyntaxError?'Invalid JSON file.':error.message);}};reader.readAsText(file);}
function openDataModal(){openModal(`<span class="eyebrow">YOUR DATA</span><h2 id="modalTitle">Backup and restore</h2><p class="modal-subtitle">Your progress, imported roadmaps and priority order are stored locally in this browser.</p><div class="data-grid"><div class="data-option"><strong>Export progress</strong><p>Download roadmaps, completed topics, notes, activity and focus time as JSON.</p><button class="secondary-btn" id="exportData">Download backup</button></div><div class="data-option"><strong>Import progress</strong><p>Restore a previous NeuralPath backup on this device.</p><button class="secondary-btn" id="importData">Choose file</button></div></div><div class="modal-actions"><button class="danger-btn" id="resetData">Reset all progress</button></div>`);document.querySelector('#exportData').onclick=exportData;document.querySelector('#importData').onclick=()=>document.querySelector('#importInput').click();document.querySelector('#resetData').onclick=()=>{if(confirm('Reset every checkmark, note, roadmap and focus session? This cannot be undone.')){state={...defaultState,completed:{},subCompleted:{},notes:{},timelines:{},activity:[],filters:{ai:'all',dl:'all'},openPhases:{},openTopics:{},customRoadmaps:{},roadmapOrder:[...defaultState.roadmapOrder],deletedRoadmaps:[]};refreshRoadmapRegistry();saveState();closeModal();rerender();showToast('Progress reset');openProfileEditor(true);}};}
function exportData(){const blob=new Blob([JSON.stringify({...state,exportedAt:new Date().toISOString()},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`neuralpath-backup-${today()}.json`;a.click();URL.revokeObjectURL(url);showToast('Backup downloaded');}
function importData(file){const reader=new FileReader();reader.onload=()=>{try{const parsed=JSON.parse(reader.result);state={...defaultState,...parsed,customRoadmaps:{...(parsed.customRoadmaps||{})},roadmapOrder:[...(parsed.roadmapOrder||defaultState.roadmapOrder)],deletedRoadmaps:[...(parsed.deletedRoadmaps||[])]};refreshRoadmapRegistry();saveState();closeModal();rerender();showToast('Progress restored');}catch{showToast('That backup file is not valid.');}};reader.readAsText(file);}

function renderSearch(q){setHeader('SEARCH','Find anything in your learning path.');const results=everyTopic().filter(t=>`${t.name} ${t.description} ${t.phaseTitle} ${roadmaps[t.trackKey].name}`.toLowerCase().includes(q.toLowerCase()));document.querySelector('#app').innerHTML=`<div class="search-results"><p class="search-result-note">${q?`${results.length} result${results.length===1?'':'s'} for “${escapeHtml(q)}”`:'Start typing to search both roadmaps.'}</p><div class="panel">${results.length?results.map(t=>topicRow(t).replace(escapeHtml(t.name),highlight(t.name,q)).replace(escapeHtml(t.description),highlight(t.description,q))).join(''):'<div class="empty-card">No matching topics found.</div>'}</div></div>`;}

document.addEventListener('click',e=>{const view=e.target.closest('[data-view]');if(view){e.preventDefault();navigate(view.dataset.view);return;}const topicEl=e.target.closest('[data-topic-id]');const action=e.target.closest('[data-action]');if(topicEl&&action){const id=topicEl.dataset.topicId;if(action.dataset.action==='toggle')toggleTopic(id);if(action.dataset.action==='subtoggle')toggleSubtopic(id,Number(action.dataset.subIndex));if(action.dataset.action==='note')openNote(id);if(action.dataset.action==='subnote')openNote(id,Number(action.dataset.subIndex));if(action.dataset.action==='topic'){const shell=action.closest('.topic-shell'),willOpen=!shell.classList.contains('open');state.openTopics[id]=willOpen;action.setAttribute('aria-expanded',String(willOpen));shell.classList.toggle('open',willOpen);saveState();}return;}if(action?.dataset.action==='roadmap-up'||action?.dataset.action==='roadmap-down'){moveRoadmap(action.dataset.roadmapId,action.dataset.action==='roadmap-up'?-1:1);updateSidebar();openRoadmapManager();return;}if(action?.dataset.action==='roadmap-delete'){const id=action.dataset.roadmapId,name=roadmaps[id].name;if(confirm(`Remove ${name}? Its learning data will be preserved.`)){deleteRoadmap(id);updateSidebar();openRoadmapManager();rerender();showToast(`${name} removed`);}return;}if(action?.dataset.action==='phase-timeline'){const track=action.dataset.track,index=Number(action.dataset.phaseIndex);openTimeline(`phase-${track}-${index}`,roadmaps[track].phases[index].title);return;}if(action?.dataset.action==='phase'){const card=action.closest('.phase-card'),key=card.dataset.phase;state.openPhases[key]=!card.classList.contains('open');saveState();card.classList.toggle('open');return;}const filter=e.target.closest('[data-filter]');if(filter){state.filters[filter.dataset.track]=filter.dataset.filter;saveState();renderRoadmap(filter.dataset.track);}});
document.querySelector('#themeButton').onclick=()=>{state.theme=state.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=state.theme;document.querySelector('#themeButton').textContent=state.theme==='dark'?'☼':'☾';saveState();};
document.querySelector('#searchButton').onclick=()=>{const panel=document.querySelector('#searchPanel');panel.classList.toggle('hidden');if(!panel.classList.contains('hidden')){document.querySelector('#globalSearch').focus();renderSearch('');}else rerender();};
document.querySelector('#globalSearch').addEventListener('input',e=>renderSearch(e.target.value.trim()));
document.querySelector('#globalSearch').addEventListener('keydown',e=>{if(e.key==='Escape'){document.querySelector('#searchPanel').classList.add('hidden');rerender();}});
document.querySelector('#dataButton').onclick=openDataModal;document.querySelector('#modalClose').onclick=closeModal;document.querySelector('#modalBackdrop').addEventListener('click',e=>{if(e.target.id==='modalBackdrop')closeModal();});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal();if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();document.querySelector('#searchButton').click();}});
document.querySelector('#editProfile').onclick=()=>openProfileEditor(false);
document.querySelector('#importInput').addEventListener('change',e=>{if(e.target.files[0])importData(e.target.files[0]);e.target.value='';});
document.querySelector('#addRoadmapButton').onclick=openAddRoadmapModal;document.querySelector('#manageRoadmapsButton').onclick=openRoadmapManager;
document.querySelector('#roadmapInput').addEventListener('change',e=>{if(e.target.files[0])importRoadmapFile(e.target.files[0]);e.target.value='';});

document.documentElement.dataset.theme=state.theme;document.querySelector('#themeButton').textContent=state.theme==='dark'?'☼':'☾';updateSidebar();navigate(state.activeView||'overview');if(profileNeedsSetup(state))openProfileEditor(true);
